"""
Django settings for campus_competition_backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
import io
# Windows 控制台默认 GBK 编码无法处理 PDF 复制文本中的特殊 Unicode 字符（如 ⼤ U+2F24），
# 强制 stdout/stderr 使用 UTF-8，避免日志写入时 UnicodeEncodeError
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== 安全配置（开发环境） ====================
# TODO（生产环境部署前必须修改以下三项）：
#   1. SECRET_KEY — 使用环境变量或配置文件注入，不要硬编码
#   2. DEBUG — 设置为 False，避免泄露错误堆栈和敏感配置
#   3. ALLOWED_HOSTS — 设置为实际的域名列表，不要使用通配符 '*'
SECRET_KEY = 'django-insecure-q02_^r%1hujbu5nwp+c8-dd6zd9#%^=y_7op==og#80ovd=g-j'
DEBUG = True
ALLOWED_HOSTS = ['*']

# Application definition

# 注册应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # 新增，放在rest_framework前面
    'rest_framework',
    'rag',  # RAG智能问答
    'api',
    'rest_framework_simplejwt'
]

# 中间件配置
MIDDLEWARE = [
    'api.middlewares.GlobalExceptionMiddleware',  # 全局异常处理（必须放在最前面）
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middlewares.OperationLogMiddleware',
]

# 跨域配置（开发环境）
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['*']

ROOT_URLCONF = 'campus_competition_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campus_competition_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL数据库配置
# TODO（生产环境）：将数据库凭据迁移到环境变量中，避免硬编码
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'campus_competition',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'CHARSET': 'utf8mb4',
    }
}

# 自定义用户模型
AUTH_USER_MODEL = 'api.User'
REST_FRAMEWORK = {
    # 全局默认：所有人都能访问，需要权限的接口单独配置
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 认证配置保留，支持token登录
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/




# 静态文件+媒体文件配置
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== RAG 智能问答配置 ====================
# 所有值可通过环境变量覆盖，默认值对应开发环境

RAG_CONFIG = {
    # --- 模型路径 ---
    'MODELS_DIR': BASE_DIR / 'models',

    # --- 大模型（阿里云 DashScope）---
    'LLM_MODEL': os.getenv('RAG_LLM_MODEL', 'qwen-plus'),
    'DASHSCOPE_API_KEY': os.getenv('DASHSCOPE_API_KEY',
        'sk-ws-H.RPXPRLD.pAgB.MEQCIBoEzAY-LMBuoHfOpxP3jeiw4LRPNeyvpsg4JxIA1pQaAiBFKRB527U0ezEVfBLc20FRzq6An8JMvjuQgH3tlxXR1w'),
    'DASHSCOPE_BASE_URL': os.getenv('DASHSCOPE_BASE_URL',
        'https://dashscope.aliyuncs.com/compatible-mode/v1'),

    # --- Milvus 向量数据库 ---
    'MILVUS_HOST': os.getenv('MILVUS_HOST', '127.0.0.1'),
    'MILVUS_PORT': int(os.getenv('MILVUS_PORT', '19530')),
    'MILVUS_DATABASE_NAME': os.getenv('MILVUS_DATABASE_NAME', 'itcast'),
    'MILVUS_COLLECTION_NAME': os.getenv('MILVUS_COLLECTION_NAME', 'edurag_gz7'),

    # --- Redis（Django 缓存用，与 CACHES 配置对应）---
    'REDIS_HOST': os.getenv('RAG_REDIS_HOST', '127.0.0.1'),
    'REDIS_PORT': int(os.getenv('RAG_REDIS_PORT', '6379')),
    'REDIS_PASSWORD': os.getenv('RAG_REDIS_PASSWORD', ''),
    'REDIS_DB': int(os.getenv('RAG_REDIS_DB', '0')),

    # --- 检索参数 ---
    'PARENT_CHUNK_SIZE': int(os.getenv('RAG_PARENT_CHUNK_SIZE', '1200')),
    'CHILD_CHUNK_SIZE': int(os.getenv('RAG_CHILD_CHUNK_SIZE', '300')),
    'CHUNK_OVERLAP': int(os.getenv('RAG_CHUNK_OVERLAP', '50')),
    'RETRIEVAL_K': int(os.getenv('RAG_RETRIEVAL_K', '10')),
    'CANDIDATE_M': int(os.getenv('RAG_CANDIDATE_M', '3')),

    # --- 应用参数 ---
    'VALID_SOURCES': os.getenv('RAG_VALID_SOURCES', 'ai,java,test,ops,bigdata').split(','),
    'CUSTOMER_SERVICE_PHONE': os.getenv('RAG_CUSTOMER_SERVICE_PHONE', '10086'),
}

# ==================== Django Redis 缓存配置 ====================
_redis_password = RAG_CONFIG['REDIS_PASSWORD']
_redis_options = {
    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
}
if _redis_password:
    _redis_options['PASSWORD'] = _redis_password

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{RAG_CONFIG['REDIS_HOST']}:{RAG_CONFIG['REDIS_PORT']}/{RAG_CONFIG['REDIS_DB']}",
        'OPTIONS': _redis_options,
        'KEY_PREFIX': 'rag',
        'TIMEOUT': 86400,  # 24 小时（匹配源项目 FQA 缓存 TTL）
    }
}

# ==================== 日志配置 ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s - %(levelname)s - %(name)s - %(module)s:%(lineno)d - %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / 'rag.log'),
            'formatter': 'verbose',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
        },
    },
    'loggers': {
        'rag': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
