# Generated by Django 5.2.11 on 2026-04-13 17:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='广告标题')),
                ('image', models.ImageField(upload_to='advert/', verbose_name='广告图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='跳转链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '赛事分类',
                'verbose_name_plural': '赛事分类',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='留言标题')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('intro', models.TextField(blank=True, max_length=200, null=True, verbose_name='个人简介')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], default='user', max_length=10, verbose_name='角色')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='竞赛标题')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面')),
                ('description', models.TextField(blank=True, null=True, verbose_name='赛事简介')),
                ('level', models.CharField(choices=[('school', '校级'), ('city', '市级'), ('province', '省级'), ('national', '国家级')], max_length=20, verbose_name='等级')),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='报名时间')),
                ('organizer', models.CharField(max_length=100, verbose_name='组织方')),
                ('competition_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='竞赛时间')),
                ('location', models.CharField(max_length=200, verbose_name='竞赛地点')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('ended', '已结束')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('request_url', models.CharField(max_length=255, verbose_name='请求URL')),
                ('ip_address', models.GenericIPAddressField(verbose_name='操作IP地址')),
                ('user_agent', models.TextField(verbose_name='浏览器/设备信息')),
                ('error_message', models.TextField(verbose_name='异常信息')),
                ('error_traceback', models.TextField(verbose_name='异常堆栈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '错误日志',
                'verbose_name_plural': '错误日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='登录用户名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='登录IP地址')),
                ('user_agent', models.TextField(verbose_name='浏览器/设备信息')),
                ('status', models.CharField(choices=[('success', '登录成功'), ('failed', '登录失败')], default='success', max_length=20, verbose_name='登录状态')),
                ('fail_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='失败原因')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('request_url', models.CharField(max_length=255, verbose_name='请求URL')),
                ('ip_address', models.GenericIPAddressField(verbose_name='操作IP地址')),
                ('user_agent', models.TextField(verbose_name='浏览器/设备信息')),
                ('duration', models.IntegerField(verbose_name='请求耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='报名姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('school', models.CharField(max_length=100, verbose_name='所属学校')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('file_url', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('status', models.CharField(choices=[('normal', '正常'), ('canceled', '已取消'), ('finished', '已完成')], default='normal', max_length=20, verbose_name='报名状态')),
                ('score', models.CharField(blank=True, max_length=50, null=True, verbose_name='赛事成绩')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.competition', verbose_name='所属赛事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
