# Generated by Django 5.2.11 on 2026-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='附件地址'),
        ),
    ]
