# Generated by Django 5.2.11 on 2026-04-14 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registration_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.CreateModel(
            name='UserCompetitionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competition', verbose_name='赛事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '赛事浏览记录',
                'verbose_name_plural': '赛事浏览记录',
                'indexes': [models.Index(fields=['user', 'competition', 'viewed_at'], name='api_usercom_user_id_5aad16_idx')],
            },
        ),
    ]
