# Generated by Django 5.2.11 on 2026-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=36, verbose_name='会话ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(verbose_name='系统回答')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='对话时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'db_table': 'rag_conversation',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FqaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='学科名称')),
                ('question', models.CharField(max_length=500, unique=True, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
            ],
            options={
                'verbose_name': 'FQA问答对',
                'verbose_name_plural': 'FQA问答对',
                'db_table': 'rag_fqa_entry',
            },
        ),
    ]
