# Generated by Django 5.2.11 on 2026-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('stored_name', models.CharField(max_length=255, verbose_name='存储文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='完整存储路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('file_type', models.CharField(max_length=10, verbose_name='文件类型')),
                ('source', models.CharField(default='general', max_length=50, verbose_name='学科分类')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='uploaded', max_length=20, verbose_name='处理状态')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='切分子块数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'db_table': 'rag_knowledge_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='fqaentry',
            name='question',
            field=models.CharField(max_length=255, unique=True, verbose_name='问题'),
        ),
    ]
